# Software

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

```{r results='asis'}
gsheet2tbl("https://docs.google.com/spreadsheets/d/1qbMpXHXm41q69prUVjpQFfP_mMXjORNxFP_IbAoCuKo/edit#gid=1692561333") %>%
  select(markdown) %>%
  mutate(markdown = str_replace_all(markdown, "\\{|\\}", ""),
         markdown = str_replace_all(markdown, "Schmidt, A.", "**Schmidt, A.**")) %>%
  pull(markdown) -> software
  cat(paste(software), sep = '\n\n')

```


\endgroup

# Selected Publications

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

```{r results='asis'}
gsheet2tbl("https://docs.google.com/spreadsheets/d/1qbMpXHXm41q69prUVjpQFfP_mMXjORNxFP_IbAoCuKo/edit#gid=0") %>%
  slice(1) %>%
  add_row(
gsheet2tbl("https://docs.google.com/spreadsheets/d/1qbMpXHXm41q69prUVjpQFfP_mMXjORNxFP_IbAoCuKo/edit#gid=1558956454")) %>%
  select(markdown) %>% 
  add_row(
    gsheet2tbl("https://docs.google.com/spreadsheets/d/1qbMpXHXm41q69prUVjpQFfP_mMXjORNxFP_IbAoCuKo/edit#gid=1473597883") %>%
  select(markdown) %>%
  slice(-1:-6)
  ) %>%
  mutate(date = str_extract(markdown,  "(?<=\\().+?(?=\\))"),
         date = parse_number(date)
         ) %>% arrange(-date) %>%
  select(markdown) %>%
  mutate(markdown = str_replace_all(markdown, "\\{|\\}", ""),
         markdown = str_replace_all(markdown, "Schmidt, A.", "**Schmidt, A.**")) %>%

  pull(markdown) -> preprints
  cat(paste(preprints), sep = '\n\n')

```


\endgroup

# Selected Conference Papers and Presentations

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<!-- ::: {#refs_anthony_conf_intl} -->
<!-- ::: -->

```{r results='asis'}
gsheet2tbl("https://docs.google.com/spreadsheets/d/1qbMpXHXm41q69prUVjpQFfP_mMXjORNxFP_IbAoCuKo/edit#gid=318960497") %>%
  filter(category != "workshops") %>%
    filter(category != "invited") %>%
    filter(category != "campus talks") %>%
  select(markdown) %>%
  mutate(markdown = str_replace_all(markdown, "\\{|\\}", ""),
         markdown = str_replace_all(markdown, "Schmidt, A.", "**Schmidt, A.**")) %>%
  slice(1,2,15,6) %>%
  pull(markdown) -> intl
  cat(paste(intl), sep = '\n\n')

```

\endgroup
